version: '3.7'

volumes:
  peer0.org3.leadersofdigitalsvo.ru:

networks:
  amigos:
    name: fabric_amigos

services:

  peer0.org3.leadersofdigitalsvo.ru:
    container_name: peer0.org3.leadersofdigitalsvo.ru
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_amigos
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org3.leadersofdigitalsvo.ru
      - CORE_PEER_ADDRESS=peer0.org3.leadersofdigitalsvo.ru:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.leadersofdigitalsvo.ru:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.leadersofdigitalsvo.ru:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.leadersofdigitalsvo.ru:11051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        - ../../organizations/peerOrganizations/org3.leadersofdigitalsvo.ru/peers/peer0.org3.leadersofdigitalsvo.ru/msp:/etc/hyperledger/fabric/msp
        - ../../organizations/peerOrganizations/org3.leadersofdigitalsvo.ru/peers/peer0.org3.leadersofdigitalsvo.ru/tls:/etc/hyperledger/fabric/tls
        - peer0.org3.leadersofdigitalsvo.ru:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 11051:11051
    networks:
      - amigos
